# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir E:/Dropbox/Learning/LearningVHDL_FPGA/Byte2Dec/Byte2Dec.cache/wt [current_project]
set_property parent.project_path E:/Dropbox/Learning/LearningVHDL_FPGA/Byte2Dec/Byte2Dec.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
read_vhdl -library xil_defaultlib E:/Dropbox/Learning/LearningVHDL_FPGA/Byte2Dec/Byte2Dec.srcs/sources_1/new/Byte2Dec.vhd
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/Dropbox/Learning/LearningVHDL_FPGA/Byte2Dec/Byte2Dec.srcs/constrs_1/new/Byte2Dec.xdc
set_property used_in_implementation false [get_files E:/Dropbox/Learning/LearningVHDL_FPGA/Byte2Dec/Byte2Dec.srcs/constrs_1/new/Byte2Dec.xdc]


synth_design -top Byte2Dec -part xc7a35tcpg236-1


write_checkpoint -force -noxdef Byte2Dec.dcp

catch { report_utilization -file Byte2Dec_utilization_synth.rpt -pb Byte2Dec_utilization_synth.pb }
